 SELECT CITY, CITY_LENGTH FROM ( SELECT TOP 1 CITY, LEN(CITY) AS CITY_LENGTH FROM STATION ORDER BY LEN(CITY) ASC, CITY ASC ) AS ShortestCity

UNION ALL

SELECT CITY, CITY_LENGTH FROM ( SELECT TOP 1 CITY, LEN(CITY) AS CITY_LENGTH FROM STATION ORDER BY LEN(CITY) DESC, CITY ASC ) AS LongestCity;
